version: '3'

services:
  emr-nure-mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - emr-nure-mongo:/var/lib/emr-nure-mongo/data

volumes:
  emr-nure-mongo:
